# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sigelowebapi:
    image: sigelowebapi
    build:
      context: .
      dockerfile: Sigelo.WebApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5063:5063
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
