# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sigelowebapi:
    image: sigelowebapi
    build:
      context: .
      dockerfile: Sigelo.WebApi/Dockerfile
    ports:
      - 5063:5063
